### ISSUE TITLE
Change military command center to just command center

### ISSUE THREAD

**Issue by dlublin** [Synopsis/CinemaNet#21]
I think if in the future we add other kinds of 'command centers' (eg the control room for a TV network or NASA) we will get a lot of conflict with this category. The differentiating factor would likely be the clothing that people are wearing.

I would suggest we go for 'command center' as a catch all for military and civilian, and include the visually similar concept of 'control room' as well.

**Comment by dlublin** [comment]
Also see 'stock market command center' 'subway command center' 'power plant command center' 'security command center'

**Comment by vade** [comment]
Resolved by just using command center for now.
