### ISSUE TITLE
More room types needed

### ISSUE THREAD

**Issue by dlublin** [Synopsis/CinemaNet#6]
For each type of building there should be at least one type of room that is somewhat unique to that type of building, but some overlap is to be expected here.

**Homes:**

For shot.location.building.apartment
shot.location.room.hallway
shot.location.room.living
shot.location.room.dining
shot.location.room.kitchen
shot.location.room.bed
shot.location.room.bath
shot.location.room.closet
shot.location.room.study
shot.location.room.stairwell
shot.location.room.elevator

For shot.location.building.house we can add
shot.location.room.garage

For shot.location.building.mansion we can add
shot.location.room.entrance

For shot.location.building.castle we can add
shot.location.room.dungeon
shot.location.room.throne

**Workplaces / Places of Business / etc**

For shot.location.building.school we can add
shot.location.room.class
shot.location.room.cafeteria

For shot.location.building.office we can add
shot.location.room.office
shot.location.room.openoffice
shot.location.room.conference

For shot.location.building.factory we can add
shot.location.room.factory
shot.location.room.warehouse

For shot.location.building.farm we can add
shot.location.room.barn

For shot.location.building.restaurant we can add
(commercial kitchen? commercial dining room? should these be differentiated from home versions?)

For shot.location.building.bar we can add
shot.location.room.bar

For shot.location.building.cafe we can add
shot.location.room.cafe

For shot.location.building.stadium we can add
shot.location.room.arena
shot.location.room.seating

For shot.location.building.theater (hall) we can add
shot.location.room.stage

For shot.location.building.store we can add
shot.location.room.aisle
shot.location.room.store
shot.location.room.checkout

For shot.location.building.mall we can add
shot.location.room.mall

**Places of Worship:**

For shot.location.building.church we can add
shot.location.room.nave
shot.location.room.pulpit

For shot.location.building.mosque we can add
shot.location.room.prayerhall

For shot.location.building.synagogue we can add
shot.location.room.synagogue

For shot.location.building.temple we can add
shot.location.room.meditation
shot.location.room.grandhall

For shot.location.building.cathedral we can add
shot.location.room.crypt

For shot.location.building.monastery we can add 
shot.location.room.cloister

**Comment by vade** [comment]
Im thinking we can exchange `building` for `exterior` and `room` for `interior` - this gives us more wiggle room with the concepts I think and is still accurate. It also allows us to do exterior.<nature scene> - rather than have another concept.


As far as rooms (or now `interior`) if we want to do that - we could have :

`lobby` for `apartment` , and `house` / `mansion` could have `foyer` - and drop `entrance` as its fairly bland?

Should add `basement` for house

Is cafe interior different enough from restaurant to be meaningful? I guess so?

[temple grand hall seems.. tricky?](https://www.google.com/search?client=safari&rls=en&biw=1245&bih=1089&tbm=isch&sa=1&ei=Qo8bXfSqKq6xgge_mZLABA&q=temple+grand+hall+interior&oq=temple+grand+hall+interior&gs_l=img.3...2746.3890..3986...0.0..0.72.507.9......0....1..gws-wiz-img.......0i8i30.3hqYJZy3wT8)

Ill continue to amend comments. Let me know your thoughts on `interior` / `exterior` rather than `room` / `building`

**Comment by vade** [comment]
Also township -> exterior.

**Comment by vade** [comment]
Ok!

Heres my proposal for location based on your feedback:


### shot.location (WIP)
>How do we describe the location of the subject / camera in the image, if any? Borrows heavily from ideas in Places 365
* `shot.location.na` (not applicable)
* `shot.location.interior` (indoors / inside)
* `shot.location.exterior` (outdoors / outside)

>Specific nature (exterior) categories if we can identify them
* `shot.location.exterior.beach`
* `shot.location.exterior.cave` (cave entrance)
* `shot.location.exterior.desert`
* `shot.location.exterior.plains`
* `shot.location.exterior.wetland`
* `shot.location.exterior.hills`
* `shot.location.exterior.forest`
* `shot.location.exterior.mountain`
* `shot.location.exterior.polar` (artic, antartic)
* `shot.location.exterior.river`
* `shot.location.exterior.lake`
* `shot.location.exterior.ocean`
* `shot.location.exterior.canyon`
* `shot.location.exterior.glacier`
* `shot.location.exterior.space`
* `shot.location.exterior.sky`

>Specific township (exterior) categories if we can identify them
* `shot.location.exterior.city`
* `shot.location.exterior.town`
* `shot.location.exterior.suburb` 
* `shot.location.exterior.park`
* `shot.location.exterior.playground`
* `shot.location.exterior.sidewalk`
* `shot.location.exterior.street` 

>Specific building (exterior) categories if we can identify them
* `shot.location.exterior.house`
* `shot.location.exterior.mansion`
* `shot.location.exterior.apartment`
* `shot.location.exterior.castle`
* `shot.location.exterior.skyscraper`
* `shot.location.exterior.palace`
* `shot.location.exterior.office`
* `shot.location.exterior.factory`
* `shot.location.exterior.farm`
* `shot.location.exterior.restaurant`
* `shot.location.exterior.bar` (or pub)
* `shot.location.exterior.cafe`
* `shot.location.exterior.chruch`
* `shot.location.exterior.mosque`
* `shot.location.exterior.synagogue`
* `shot.location.exterior.temple`
* `shot.location.exterior.cathedral`
* `shot.location.exterior.monastery`
* `shot.location.exterior.stadium`
* `shot.location.exterior.theater` 
* `shot.location.exterior.garage`
* `shot.location.exterior.store`
* `shot.location.exterior.mall`
* `shot.location.exterior.port`
* `shot.location.exterior.pier`
* `shot.location.exterior.warehouse`
* `shot.location.exterior.ruins`
* `shot.location.exterior.concerthall`
* `shot.location.exterior.nightclub`
* `shot.location.exterior.buildng.airport`
* `shot.location.exterior.station.train`
* `shot.location.exterior.station.gas`
* `shot.location.exterior.station.bus`
* `shot.location.exterior.station.subway`
* `shot.location.exterior.hospital`
* `shot.location.exterior.school`
* `shot.location.exterior.library`
* `shot.location.exterior.parkinglot`
* `shot.location.exterior.bridge`
* `shot.location.exterior.tunnel` (entrance)


>Specific vehicle (exterior) categories if we can identify them
* `shot.location.exterior.car`
* `shot.location.exterior.bus`
* `shot.location.exterior.motorcycle`
* `shot.location.exterior.bicycle`
* `shot.location.exterior.truck`
* `shot.location.exterior.train`
* `shot.location.exterior.boat`
* `shot.location.exterior.airplane`
* `shot.location.exterior.spacecraft`


>Specific room (interior) categories if we can identify them
* `shot.location.interior.cave`
* `shot.location.interior.lobby`
* `shot.location.interior.foyer`
* `shot.location.interior.hallway`
* `shot.location.interior.livingroom`
* `shot.location.interior.diningroom`
* `shot.location.interior.kitchen`
* `shot.location.interior.closet`
* `shot.location.interior.bedroom`
* `shot.location.interior.bathroom`
* `shot.location.interior.closet`
* `shot.location.interior.garage`
* `shot.location.interior.auditorium`
* `shot.location.interior.gym`
* `shot.location.interior.emergencyroom`
* `shot.location.interior.study`
* `shot.location.interior.stairwell`
* `shot.location.interior.elevator`
* `shot.location.interior.garage` (factory line, factory floor)
* `shot.location.interior.factory` (factory line, factory floor)
* `shot.location.interior.warehouse` 
* `shot.location.interior.dungeon` 
* `shot.location.interior.throneroom` 
* `shot.location.interior.classroom`
* `shot.location.interior.cafeteria`
* `shot.location.interior.office`
* `shot.location.interior.openoffice`
* `shot.location.interior.conferenceroom`
* `shot.location.interior.barn`
* `shot.location.interior.restaurant`
* `shot.location.interior.commercialkitchen`
* `shot.location.interior.bar`
* `shot.location.interior.cafe`
* `shot.location.interior.arena`
* `shot.location.interior.stage`
* `shot.location.interior.aisle` (store)
* `shot.location.interior.dancefloor`
* `shot.location.interior.store`
* `shot.location.interior.checkout`
* `shot.location.interior.mall`
* `shot.location.interior.nave`
* `shot.location.interior.pulpit`
* `shot.location.interior.prayerhall`
* `shot.location.interior.synegogue`
* `shot.location.interior.meditation`
* `shot.location.interior.grandhall`
* `shot.location.interior.crypt`
* `shot.location.interior.cloister`

>Specific vehicle (interior) if we can identify them
* `shot.location.interior.car`
* `shot.location.interior.bus`
* `shot.location.interior.truck`
* `shot.location.interior.train`
* `shot.location.interior.boat` 
* `shot.location.interior.airplane` (cockpit, cabin)
* `shot.location.interior.spacecraft` (cockpit, cabin)

**Comment by vade** [comment]
Remove external factory  and add external 'industrial plant' (factory buildings are indistinguishable from warehouses or other office buildings in the results AFAICT).

**Comment by vade** [comment]
Nighclub entrance is problematic:

a) mostly returns 'shootings' / police incidents (pulse) :'(
b) they aren't really a style. 

Thinking of dropping the attribute (interior / dance floor / bar is still there tho)

**Comment by vade** [comment]
Park is tricky - do we mean:

* national park (no)
* city park
* water park
 etc.

Hmmmm...

**Comment by vade** [comment]
Remove concert hall - its effectively theater with a different usage?

**Comment by vade** [comment]
Remove Bus Station -> Bus Stop, the buildings are.. not very unique and really its a bus stop most in use.

**Comment by dlublin** [comment]
We should add prison / detention center to locations, both interior and exterior.

**Comment by vade** [comment]
Very timely sadly.

**Comment by vade** [comment]
So we're getting some dismal scores, and in looking at AutoML's confusion matrix, we might want to think about some things

* cafe, bar and restaurant are confused
* garage and house are confused

Possible solutions

* collapse cafe bar, restaurant to one building type ? Or see if we can remove confusion by being more specific with the type of entity we mean? Ie, external cafe and external restaurant are basically the same. Is there a better way to differentiate (or, collapse to 'eatery'?)

* remove 'garage' and maybe do 'auto shop' or 'auto repair shop building'  as a 'House with Garage' and a 'Garage attached to a House' are sort of the same visual entity as it stands (thus the confusion)

**Comment by dlublin** [comment]
1.  I think collapsing cafe / bar / restaurant into a single category is a good idea. We'll make sure that the 'human readable description' string for the category indicates that it covers all three.
2. Auto shop is good to remove the confusion between commercial and residential garages, and I think it is okay if 'house with garage' and 'house' are the same thing.

**Comment by vade** [comment]
I was thinking 'house' can be a super set of houses, some of which may have a garage. and a home garage should (would, and does now due to confusion) trigger 'House' label.

So "auto repair garage" (or whatever, auto shop) isn't confused with house.
house contains house and house with garage.

As for 1 - whats a good word to collapse those ideas?  Restaurant does encapsulate all of those concepts (a bar, a cafe, a cafeteria), and the interiors could point to particular features, like 'just the bar area', 'dining room') ? 

Also I think interiors can take a cue for

**Comment by dlublin** [comment]
I think 'restaurant' is a fine catch-all to include cafe / bars.

**Comment by vade** [comment]
99% resolved, closing
