### ISSUE TITLE
Interior data set searches trend towards empty rooms

### ISSUE THREAD

**Issue by vade** [Synopsis/CinemaNet#8]
For example, 'dining room' as a google image search results in images of abstract dining table setups devoid of people, on white backgrounds, etc.

Suggest we update searches to be

* 'dining room' -> 'people eating dinner at home'
* 'kitchen' -> 'people cooking at home'

One issue with this approach is, Google only fucking shows us white people. *sigh*

**Comment by dlublin** [comment]
So, I've mentioned this before, but I'll add it in here again – I've got a huge dump of images that are just straight up captured from TV that I think can round out this issue. It is more of a dumpster diving approach vs pruning, but it tends to have lots of images with people. Broadcast TV also has more diversity and I can also tune the capture to some of the foreign channels to widen that net.

**Comment by vade** [comment]
Sure, but the issue there is - we can't 'isolate' our search terms so we'd have to manually assign the categories. I think its a good idea, can we search by show? 

I honestly think tuning our searches will be a bit better. How do you propose using a giant set of images with no organization and putting those images into our proposed class folders?

Real q - not being shady, I want to find a solution! :D

**Comment by vade** [comment]
Maybe a 'life hack' is to mine existing data sets like Places365 and sort of port them to our label format?

**Comment by dlublin** [comment]
In this case I figure we are just looking to balance out the issues with the existing data sets, ie add like 50-100 more images that include people. If we relied just on images from TV, it would probably have the reverse problem of always having humans.

I started cataloguing some of the tv image dumps at some point to get a sense of the process, it goes faster than you'd think. Pick a category, scan through the image dump until you find something and copy it over and repeat. You can drop into the collection pretty much anywhere, most any show you run into is going to have shots in all kinds of random locations, not to mention commercials; even the news has on location stuff that fits. If you'd like I can send over a small batch for you to try for yourself!

**Comment by vade** [comment]
This is mostly resolved by having updated a plethora of search terms in the script.
