### ISSUE TITLE
Improve shot.location classification scores

### ISSUE THREAD

**Issue by dlublin** [Synopsis/CinemaNet#9]
The classification scores on some of the shot location data sets are very low, or generally under performing, especially on recall.

On a first pass, I think the 'none of the above' folders can be improved.

In particular the 'shot_location_exterior_nature' and 'shot_location_exterior_buildings' data sets seemed particularly bad so I used these as a starting point.
(whereas eg shot_location_exterior_township1 is already scoring in the mid-80's in both precision and recall and may just need to be tightened up, or it makes some sense that we would see some confusion between some of the categories like suburbs vs towns)

I've just done a first attempt to improve 'shot_location_exterior_nature' and 'shot_location_exterior_buildings' by adding images from their opposite data sets (eg some shots from nature in the not buildings folder, and some shots from buildings to the nature folder)

If that seems to improve the recall results for exterior buildings and nature, we can apply the same approach to some of the other categories that seem to have the same issue.

**Comment by vade** [comment]
Awesome. Thanks. Ill re-upload those new data sets and train them now.

**Comment by dlublin** [comment]
Ok that didn't work. Next up, as mentioned in some of the other issue threads, combining and cleaning up some of the data sets based on the confusion matrix seems to be a good idea.

Along with restaurant / cafe / bar which is discussed in another issue, the 'library' concept seems to be particularly low scoring, and going through the image set there are definitely some examples of buildings that are easily confused for other types of buildings that can potentially be pruned out to improve that score.
